### ISSUE TITLE
Entity History does not work.

### ISSUE THREAD

**Issue by keanuplayz** [CCDirectLink/crosscode-map-editor#110]
When clicking an entry in the history selector that has anything to do with creating/editing/deleting an entity, nothing happens.

Example: 
I create an EnemySpawner, change it's position (which counts as an edit), and then delete the entity.
Next up I click the "Edited entity" entry in the history selector, to revert my deletion.
Nothing happens.

**Comment by Vegita2** [comment]
I cannot reproduce it in 0.5.0-beta.1
Your example works as it should

**Comment by keanuplayz** [comment]
Another random issue that works as it should after restarting.

Closing.
