### ISSUE TITLE
Implement an character selector.

### ISSUE THREAD

**Issue by keanuplayz** [CCDirectLink/crosscode-map-editor#115]
For NPCs, events, etc.

**Comment by Vegita2** [comment]
what's a character selector? I need some more information
- where is it used? (Event type, Entity type)
- how should it behave

**Comment by keanuplayz** [comment]
It should be used in situations like this.
![image](https://user-images.githubusercontent.com/50610755/65271318-39b1d100-db1d-11e9-94de-dbbb3ba5935a.png)

Behavior should be like a window, where you can go into a character folder (ex. bergen), and select a person. If possible, let the editor preview the person you're selecting.

**Comment by Vegita2** [comment]
Preview sounds like a nice feature.
It's not easy to implement so it might take a while until we can get that to work properly.
