### ISSUE TITLE
NPC animSheet not handling propertly

### ISSUE THREAD

**Issue by omegalink12** [CCDirectLink/crosscode-map-editor#12]
When loading NPC, it's possible for a sheet to be mistaken as a reference because they do not all have a namedSheets property. Eg "MULTI_DIR_ANIMATION". This ends up erroring later as it tries to split an object.

A better check would be to see if it's a string or has a DOCTYPE.

This can be reproduced by loading dreams.dream11

**Comment by Vegita2** [comment]
Thanks for the issue. I'll try out your suggestion in the coming days
