### ISSUE TITLE
Support nwjs

### ISSUE THREAD

**Issue by ac2pic** [CCDirectLink/crosscode-map-editor#137]

**Comment by Vegita2** [comment]
Why nwjs support? I originally switched from nwjs to electron because of auto updates

**Comment by ac2pic** [comment]
I intend to make this compatible with the "tool-launcher" project. Since it designed to be run on nwjs,  I will have to add in support for the map editor. I could opt in to maintain a fork.

**Comment by ac2pic** [comment]
It's probably better to just maintain a fork.
