### ISSUE TITLE
show folders first in Load map 

### ISSUE THREAD

**Issue by Vegita2** [CCDirectLink/crosscode-map-editor#177]
Showing folders first would make navigation simpler. My desktop file manager also always shows folders first.
Other opinions?

![image](https://user-images.githubusercontent.com/9483499/93621955-9966e480-f9dc-11ea-9a10-98bc2393a0ec.png)

**Comment by 2767mr** [comment]
I just tried it and it definitely feels better. However, for some reason I feel a bit uncomfortable with all options.

**Comment by Vegita2** [comment]
what's the alternative?

**Comment by 2767mr** [comment]
I don't have one. Lets just invert the order for now and open another issue if we find an even better way.
