### ISSUE TITLE
Ability to mark NPC Pages Event type 

### ISSUE THREAD

**Issue by inkkly** [CCDirectLink/crosscode-map-editor#188]
Add the ability to mark the event type (identified in the source code as `sc.NPC_EVENT_TYPE`) by nesting that pages event and action steps inside their respective identifiers:

## `SIMPLE`
No change, since this is the default :p 

## `TRADE`
More complicated and nuanced than the other types.
Nests `"trade":{"trader": "nameofTrader"}` inside of the event, with `nameofTrader` being set to whatever the internal name of the trader is in `database.json`:

```
"event": {
    "trade": {
        "trader": "rhombusPostHead1"
    }
}
```

It's important to note that event steps are not typically used with trade NPCs, except in rare cases like the Geta Trader, where they're usually done by nesting another `event` array inside of `trade`, and then using the `traded` and `canceled` branches of `START_NPC_TRADE_MENU`: 
```javascript
"event" :{
    "trade": {
        "event": [{
            "withBranches": true,
            "type": "START_NPC_TRADE_MENU",
            "traded": [ /*events go in here*/ ],
            "canceled": [ /*or here*/ ]
        }], 
    "trader": "sapphireGeta"
    }
}
```

Though, you could feasibly also add event steps inside of event>trade>event if you want to have a dialogue before opening the trade menu, just make sure START_NPC_TRADE_MENU is an event step so the trade still actually happens.

## `QUEST`, `SHOP`, and `ARENA`
Much simpler compared to `trade`, they simply add `quest` or `arena` arrays inside of the event, inside of which event steps are added:

```javascript
"event": {
        "quest": [
               //events go here
          ]
}
```

**Comment by 2767mr** [comment]
Closed by #221
