### ISSUE TITLE
What am I supposed to put in "CrossCode assets folder"? 

### ISSUE THREAD

**Issue by WhatNot911** [CCDirectLink/crosscode-map-editor#2]
What am I supposed to put in "CrossCode assets folder"? I don't even have one and there is no information on the nets, I just got an empty folder set in config.ts

**Comment by Vegita2** [comment]
the assets folder is inside the actual game folder, you don't have to create it or put anything there. It's the folder where all of CrossCode's assets are stored

**Comment by WhatNot911** [comment]
But what game? I don't have a game yet, I just gathering up tools for development and very much like where this map editor is going. If I do all npm inits and starts and go to localhost:4200 mapeditor doesn't load properly and seems to want some files and folder that I don't know where to obtain. I must be missing something crucial

**Comment by Vegita2** [comment]
Oh ok i understand the problem now. This map editor is actually for the game CrossCode. It can only read/write maps for that game. A general purpose editor like Tiled would probably be the better option in your case

**Comment by WhatNot911** [comment]
Oh man! That is really sad. Gosh darn it, it's even got something to do with Phaser which I plan to use in my project. I guess I'll have to use Tiled this time. What a bummer. Any ideas on when this editor will become a standalone thing for all kinds of maps if it is even planned?

**Comment by Vegita2** [comment]
It's not planned, but it's only a matter of writing an importer/exporter for other map formats. 
Problem is this editor is far from finished and misses some necessary functions to be actually useful.

You can also take a look at [ImpactJS](http://impactjs.com/). The engine comes with a map editor. That can be another option
