### ISSUE TITLE
Implement a prop selector

### ISSUE THREAD

**Issue by lexisother** [CCDirectLink/crosscode-map-editor#228]
At the moment, `propType` field on the `Prop` entity is edited like this:
![image](https://user-images.githubusercontent.com/54973868/164515808-ad863aef-e969-48be-9280-ddc0f2dc6cd4.png)

Of course, basically the only reference you have are the props that are present in native maps. Maybe it would be handy to implement some sort of "prop selector" which allows you to select a sheet and then select a prop from the sheet. (showing previews, of course)

**Comment by lexisother** [comment]
For anyone who might be interested in implementing this, here's some reference UI:

![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/54973868/7c7beeb8-087e-4b89-8863-70c11388c8ef)

**Comment by Vegita2** [comment]
Looks cool, I'll try to implement it

**Comment by XenonA7** [comment]
There's a handful of props that have multiple animations (these use different sprites). It would be ideal for a prop selector to detect these and display the different options.
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/105614278/9cf608ee-91c7-49a0-ae1f-c8e2fb59b316)
