### ISSUE TITLE
Bug: Can't set "wait" attribute inside action steps

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/crosscode-map-editor#240]
The DO_ACTION event step allows you to define a sequence of action steps. However in the action editor, any action step with a "wait" property will not be able to be set. Trying to set this property will set it for the DO_ACTION event, not the action step you are trying to edit.
![image](https://user-images.githubusercontent.com/105614278/187001251-296a92a5-c879-421c-8d56-d7705bb652ed.png)

Exiting the action editor after trying to click this checkbox will show that the "wait" property has been wrongly updated for the DO_ACTION event.

Some examples I have observed this with are the action steps SHOW_EFFECT and JUMP.

**Comment by Image-unavailable** [comment]
I experimented a bit, and this seems to occur if there are two properties with the same name in both an action step and the containing event step. Still don't know why though.

Technical note: for example, changing `wait` to `waitaa` using devtools prevents this from happening, but changing it to a property present in the event step makes it happen with that property instead.
