### ISSUE TITLE
Layer editor does not allow setting the layer to "lighter" mode

### ISSUE THREAD

**Issue by EL20202** [CCDirectLink/crosscode-map-editor#261]
While I do not think this is commonly used - a layer's rendering mode can be changed to use "lighter" as a simple boolean value.

Map taken from the map `arena.areas.autumn-setting-01`:
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/49847844/4f3e3fbf-de6c-4d41-b637-3d2359acc23a)

Map created by the map editor:
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/49847844/c165e2d7-b47f-4a2f-8f4c-9ba6e4cf55e2)

**Comment by Vegita2** [comment]
What does the property do? Is it just additive blending?
