### ISSUE TITLE
Change GlowingLine minimum size to 8

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/crosscode-map-editor#276]
The GlowingLine entity would be much easier to place if the minimum x/y size was 8. Right now you can't create a new GlowingLine entity smaller than x=16 or y=16. Here is a vanilla example where the size is using y=8, this is not currently possible in the editor when creating a new GlowingLine.

![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/105614278/fb07d660-d254-4816-b341-66073e5151ed)

**Comment by Vegita2** [comment]
Is this the only entity where that's the case?

**Comment by XenonA7** [comment]
The only potential other one I can think of is **FerroLine** but that entity isn't supported by the map editor anyways (this is from the post-game DLC).

**Comment by lexisother** [comment]
Speaking of... we should really look into supporting extensions.
