### ISSUE TITLE
WallHorizontal/WallVertical have wrong default size

### ISSUE THREAD

**Issue by EL20202** [CCDirectLink/crosscode-map-editor#291]
WallHorizontal and WallVertical are supposed to have a default fixed side size of 8, but by default it is 16 and there is no way to change it outside of entering the map file and manually setting it to 8.

How it looks in the editor:
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/49847844/9f6a24e7-6b85-491e-82c4-1da5bba438b2)

And here's how it looks in game, which is very much not how it's supposed to look:
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/49847844/092e07a0-de9c-49bc-87f0-fcb767294859)

(the same applies to WallVertical, but with swapped width/height)

**Comment by XenonA7** [comment]
What happened to this? #245

**Comment by EL20202** [comment]
I have no idea, honestly. I swear in the past it used to be the proper size of 8, but I feel some recent change must have undone it or something.

**Comment by krypciak** [comment]
Should be fixed now
