### ISSUE TITLE
Unsaved changes dialogue appearing without changes

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/crosscode-map-editor#307]
Upon opening a new map editor instance, you can freely load different maps without the "unsaved changes" dialogue. However, if you edit a map at all, the dialogue will now always pop up, even if you open a new map without changing the existing one.

Steps to reproduce:
1. Open any map.
2. Make any edit, such as moving an entity.
3. Open a different map, press "Discard changes" when the dialogue appears.
4. Open a 3rd map without editing the 2nd map. The dialogue will still appear until you reboot the map editor.

**Comment by 2767mr** [comment]
Workaround until this is fixed: Saving a map will make this go away

**Comment by XenonA7** [comment]
I have also noticed that the dialogue will pop up after you do **File -> Save Map as...** to save your map, then try to close the editor. Despite having just saved a second ago.
