### ISSUE TITLE
[Feature Request] Display tile selection size

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/crosscode-map-editor#310]
It would be very useful to display the dimensions of the current tile selection. I am referring to the tile selection achieved by going into "layers" mode and dragging right-click in the editor.

This would be useful for measuring to know if a large area is an even/odd tile count, and to get the size of paths to better align TeleportGrounds between adjacent maps. Right now this is done by manually counting tiles.

Here is a gif from the game Rimworld. It doesn't need to have fancy numbers that line up with the selection box like in this example, it would be perfectly fine to print the dimensions in the corner of the editor window as well.
![rimworld-selection-size](https://github.com/CCDirectLink/crosscode-map-editor/assets/105614278/9e88f220-0ee7-4172-8606-6df70484f7fd)

**Comment by Vegita2** [comment]
Looks nice. I'll try to add it
