### ISSUE TITLE
Resizing the window now breaks the game canvas

### ISSUE THREAD

**Issue by XenonA7** [CCDirectLink/crosscode-map-editor#319]
As of version 1.6.0, I am seeing the canvas resolution break when resizing the window. This makes opening a second session and moving it to another monitor very difficult. Restarting the map editor will fix the issue.

I suspect that the fix for https://github.com/CCDirectLink/crosscode-map-editor/issues/265 must have caused this new issue.

I am using Windows 10 with multiple 1920x1080 monitors.

![map-editor-resolution-issue](https://github.com/CCDirectLink/crosscode-map-editor/assets/105614278/2ca1b32d-a26e-49cd-93ba-4c709812a79e)

**Comment by 2767mr** [comment]
@XenonA7 Could you check whether this fixed your issue?

**Comment by XenonA7** [comment]
This works perfectly on my end!
I can also move the map editor between monitors of different resolutions just fine now, which was not possible before 1.6.0.
