### ISSUE TITLE
Can't Load Assets File

### ISSUE THREAD

**Issue by ac2pic** [CCDirectLink/crosscode-map-editor#51]
![image](https://user-images.githubusercontent.com/13393678/60601454-c3040380-9d77-11e9-89a0-0db98f5d368d.png)

**Comment by ac2pic** [comment]
Did not change any settings.

**Comment by ac2pic** [comment]
LocalStorage is empty in the second instance.

**Comment by Vegita2** [comment]
this looks like a good solution
https://github.com/electron/electron/issues/2493#issuecomment-131216836
