### ISSUE TITLE
please update typescript in webapp

### ISSUE THREAD

**Issue by meplona** [CCDirectLink/crosscode-map-editor#6]
`ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.`

please update typescript@2.9

reference: https://github.com/angular/flex-layout/issues/830

thank you

**Comment by Nnubes256** [comment]
To be fixed in #5.
