### ISSUE TITLE
add/remove options for layers/entity properties

### ISSUE THREAD

**Issue by Vegita2** [CCDirectLink/crosscode-map-editor#8]
suggested by 2hh8899[B.C.N.E]기술자

![settings](https://cdn.discordapp.com/attachments/383264360518123520/510028545909719040/Hope.png)

**Comment by 2767mr** [comment]
A lot of this has been implemented over time. Layers are now pretty much complete except for #68 . There is little reason to remove known properties from known entities. The only thing that is left of this issue is support for custom entities.

**Comment by Vegita2** [comment]
Good point. 
Custom entities should be in their own issue, probably #54
