### ISSUE TITLE
Start using the Editor

### ISSUE THREAD

**Issue by unapropriate** [CCDirectLink/crosscode-map-editor#9]
Hi, i saw this pop up on the internet a few days ago and wanted to use it. Went to the releases page, downloaded the zip, unzipped it. But after unzipping, what is the step-by-step process of using it? Where do i start?

- Keanu

**Comment by Vegita2** [comment]
The release is really old (2017) and misses quite a few features. It's better to use the source code directly. Details how to get it running are in the readme.

To use the old release you have to start `cc-map-editor.exe` and when a dialog pops up choose the path to your `crosscode/assets` folder. 
For steam it's usually `C:/Program Files (x86)/Steam/steamapps/common/CrossCode/assets/`

**Comment by Vegita2** [comment]
The Release now auto updates
